// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: local_chat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IdempotencyKey string `protobuf:"bytes,2,opt,name=idempotencyKey,proto3" json:"idempotencyKey,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*Request_SysInit
	//	*Request_Ping
	//	*Request_CheckLogin
	//	*Request_SendSmsCode
	//	*Request_SighIn
	//	*Request_SignUp
	//	*Request_Authorize
	Payload isRequest_Payload `protobuf_oneof:"payload"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_chat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_local_chat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_local_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Request) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (m *Request) GetPayload() isRequest_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Request) GetSysInit() *SysInit {
	if x, ok := x.GetPayload().(*Request_SysInit); ok {
		return x.SysInit
	}
	return nil
}

func (x *Request) GetPing() *Ping {
	if x, ok := x.GetPayload().(*Request_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *Request) GetCheckLogin() *CheckLogin {
	if x, ok := x.GetPayload().(*Request_CheckLogin); ok {
		return x.CheckLogin
	}
	return nil
}

func (x *Request) GetSendSmsCode() *SendSmsCode {
	if x, ok := x.GetPayload().(*Request_SendSmsCode); ok {
		return x.SendSmsCode
	}
	return nil
}

func (x *Request) GetSighIn() *SighIn {
	if x, ok := x.GetPayload().(*Request_SighIn); ok {
		return x.SighIn
	}
	return nil
}

func (x *Request) GetSignUp() *SighUp {
	if x, ok := x.GetPayload().(*Request_SignUp); ok {
		return x.SignUp
	}
	return nil
}

func (x *Request) GetAuthorize() *Authorize {
	if x, ok := x.GetPayload().(*Request_Authorize); ok {
		return x.Authorize
	}
	return nil
}

type isRequest_Payload interface {
	isRequest_Payload()
}

type Request_SysInit struct {
	SysInit *SysInit `protobuf:"bytes,3,opt,name=sysInit,proto3,oneof"`
}

type Request_Ping struct {
	Ping *Ping `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

type Request_CheckLogin struct {
	CheckLogin *CheckLogin `protobuf:"bytes,5,opt,name=checkLogin,proto3,oneof"`
}

type Request_SendSmsCode struct {
	SendSmsCode *SendSmsCode `protobuf:"bytes,6,opt,name=sendSmsCode,proto3,oneof"`
}

type Request_SighIn struct {
	SighIn *SighIn `protobuf:"bytes,7,opt,name=sighIn,proto3,oneof"`
}

type Request_SignUp struct {
	SignUp *SighUp `protobuf:"bytes,8,opt,name=signUp,proto3,oneof"`
}

type Request_Authorize struct {
	Authorize *Authorize `protobuf:"bytes,9,opt,name=authorize,proto3,oneof"`
}

func (*Request_SysInit) isRequest_Payload() {}

func (*Request_Ping) isRequest_Payload() {}

func (*Request_CheckLogin) isRequest_Payload() {}

func (*Request_SendSmsCode) isRequest_Payload() {}

func (*Request_SighIn) isRequest_Payload() {}

func (*Request_SignUp) isRequest_Payload() {}

func (*Request_Authorize) isRequest_Payload() {}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IdempotencyKey string `protobuf:"bytes,2,opt,name=idempotencyKey,proto3" json:"idempotencyKey,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*Response_Bool
	//	*Response_Error
	//	*Response_SysInited
	//	*Response_Pong
	//	*Response_Authorized
	Payload    isResponse_Payload `protobuf_oneof:"payload"`
	ServerTime uint64             `protobuf:"varint,1000,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_chat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_local_chat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_local_chat_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Response) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (m *Response) GetPayload() isResponse_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Response) GetBool() bool {
	if x, ok := x.GetPayload().(*Response_Bool); ok {
		return x.Bool
	}
	return false
}

func (x *Response) GetError() *Error {
	if x, ok := x.GetPayload().(*Response_Error); ok {
		return x.Error
	}
	return nil
}

func (x *Response) GetSysInited() *SysInited {
	if x, ok := x.GetPayload().(*Response_SysInited); ok {
		return x.SysInited
	}
	return nil
}

func (x *Response) GetPong() *Pong {
	if x, ok := x.GetPayload().(*Response_Pong); ok {
		return x.Pong
	}
	return nil
}

func (x *Response) GetAuthorized() *Authorized {
	if x, ok := x.GetPayload().(*Response_Authorized); ok {
		return x.Authorized
	}
	return nil
}

func (x *Response) GetServerTime() uint64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type isResponse_Payload interface {
	isResponse_Payload()
}

type Response_Bool struct {
	Bool bool `protobuf:"varint,3,opt,name=bool,proto3,oneof"`
}

type Response_Error struct {
	Error *Error `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

type Response_SysInited struct {
	SysInited *SysInited `protobuf:"bytes,5,opt,name=sysInited,proto3,oneof"`
}

type Response_Pong struct {
	Pong *Pong `protobuf:"bytes,6,opt,name=pong,proto3,oneof"`
}

type Response_Authorized struct {
	Authorized *Authorized `protobuf:"bytes,7,opt,name=authorized,proto3,oneof"`
}

func (*Response_Bool) isResponse_Payload() {}

func (*Response_Error) isResponse_Payload() {}

func (*Response_SysInited) isResponse_Payload() {}

func (*Response_Pong) isResponse_Payload() {}

func (*Response_Authorized) isResponse_Payload() {}

type Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pts uint64 `protobuf:"varint,1,opt,name=pts,proto3" json:"pts,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*Update_UserUpdated
	Payload isUpdate_Payload `protobuf_oneof:"payload"`
}

func (x *Update) Reset() {
	*x = Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_chat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_local_chat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_local_chat_proto_rawDescGZIP(), []int{2}
}

func (x *Update) GetPts() uint64 {
	if x != nil {
		return x.Pts
	}
	return 0
}

func (m *Update) GetPayload() isUpdate_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Update) GetUserUpdated() *UpdateUser {
	if x, ok := x.GetPayload().(*Update_UserUpdated); ok {
		return x.UserUpdated
	}
	return nil
}

type isUpdate_Payload interface {
	isUpdate_Payload()
}

type Update_UserUpdated struct {
	UserUpdated *UpdateUser `protobuf:"bytes,2,opt,name=userUpdated,proto3,oneof"`
}

func (*Update_UserUpdated) isUpdate_Payload() {}

var File_local_chat_proto protoreflect.FileDescriptor

var file_local_chat_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x6c, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x09, 0x73, 0x79, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0d, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9a,
	0x03, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x69, 0x64,
	0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x69, 0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4b,
	0x65, 0x79, 0x12, 0x2c, 0x0a, 0x07, 0x73, 0x79, 0x73, 0x49, 0x6e, 0x69, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x79,
	0x73, 0x49, 0x6e, 0x69, 0x74, 0x48, 0x00, 0x52, 0x07, 0x73, 0x79, 0x73, 0x49, 0x6e, 0x69, 0x74,
	0x12, 0x23, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x6c, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52,
	0x04, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x35, 0x0a, 0x0a, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x63, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x48, 0x00,
	0x52, 0x0a, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x38, 0x0a, 0x0b,
	0x73, 0x65, 0x6e, 0x64, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x6e, 0x64,
	0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x53,
	0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x68, 0x49, 0x6e,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6c, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x69, 0x67, 0x68, 0x49, 0x6e, 0x48, 0x00, 0x52, 0x06, 0x73, 0x69, 0x67, 0x68, 0x49,
	0x6e, 0x12, 0x29, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x6c, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x69, 0x67, 0x68,
	0x55, 0x70, 0x48, 0x00, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x12, 0x32, 0x0a, 0x09,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x6c, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x7a, 0x65, 0x48, 0x00, 0x52, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65,
	0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xbd, 0x02, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x69, 0x64, 0x65, 0x6d,
	0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x69, 0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00,
	0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x12, 0x26, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6c, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x32,
	0x0a, 0x09, 0x73, 0x79, 0x73, 0x49, 0x6e, 0x69, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x6c, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x79, 0x73, 0x49,
	0x6e, 0x69, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x09, 0x73, 0x79, 0x73, 0x49, 0x6e, 0x69, 0x74,
	0x65, 0x64, 0x12, 0x23, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x6c, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x48,
	0x00, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x12, 0x35, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x69, 0x7a, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x63,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64,
	0x48, 0x00, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0xe8, 0x07,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65,
	0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x5e, 0x0a, 0x06, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x70, 0x74, 0x73, 0x12, 0x37, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c,
	0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x48, 0x00, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x0a, 0x5a, 0x08, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_local_chat_proto_rawDescOnce sync.Once
	file_local_chat_proto_rawDescData = file_local_chat_proto_rawDesc
)

func file_local_chat_proto_rawDescGZIP() []byte {
	file_local_chat_proto_rawDescOnce.Do(func() {
		file_local_chat_proto_rawDescData = protoimpl.X.CompressGZIP(file_local_chat_proto_rawDescData)
	})
	return file_local_chat_proto_rawDescData
}

var file_local_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_local_chat_proto_goTypes = []interface{}{
	(*Request)(nil),     // 0: lcProto.Request
	(*Response)(nil),    // 1: lcProto.Response
	(*Update)(nil),      // 2: lcProto.Update
	(*SysInit)(nil),     // 3: lcProto.SysInit
	(*Ping)(nil),        // 4: lcProto.Ping
	(*CheckLogin)(nil),  // 5: lcProto.CheckLogin
	(*SendSmsCode)(nil), // 6: lcProto.SendSmsCode
	(*SighIn)(nil),      // 7: lcProto.SighIn
	(*SighUp)(nil),      // 8: lcProto.SighUp
	(*Authorize)(nil),   // 9: lcProto.Authorize
	(*Error)(nil),       // 10: lcProto.Error
	(*SysInited)(nil),   // 11: lcProto.SysInited
	(*Pong)(nil),        // 12: lcProto.Pong
	(*Authorized)(nil),  // 13: lcProto.Authorized
	(*UpdateUser)(nil),  // 14: lcProto.UpdateUser
}
var file_local_chat_proto_depIdxs = []int32{
	3,  // 0: lcProto.Request.sysInit:type_name -> lcProto.SysInit
	4,  // 1: lcProto.Request.ping:type_name -> lcProto.Ping
	5,  // 2: lcProto.Request.checkLogin:type_name -> lcProto.CheckLogin
	6,  // 3: lcProto.Request.sendSmsCode:type_name -> lcProto.SendSmsCode
	7,  // 4: lcProto.Request.sighIn:type_name -> lcProto.SighIn
	8,  // 5: lcProto.Request.signUp:type_name -> lcProto.SighUp
	9,  // 6: lcProto.Request.authorize:type_name -> lcProto.Authorize
	10, // 7: lcProto.Response.error:type_name -> lcProto.Error
	11, // 8: lcProto.Response.sysInited:type_name -> lcProto.SysInited
	12, // 9: lcProto.Response.pong:type_name -> lcProto.Pong
	13, // 10: lcProto.Response.authorized:type_name -> lcProto.Authorized
	14, // 11: lcProto.Update.userUpdated:type_name -> lcProto.UpdateUser
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_local_chat_proto_init() }
func file_local_chat_proto_init() {
	if File_local_chat_proto != nil {
		return
	}
	file_sys_proto_init()
	file_auth_proto_init()
	file_users_proto_init()
	file_messages_proto_init()
	file_dialogs_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_local_chat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_chat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_chat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_local_chat_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Request_SysInit)(nil),
		(*Request_Ping)(nil),
		(*Request_CheckLogin)(nil),
		(*Request_SendSmsCode)(nil),
		(*Request_SighIn)(nil),
		(*Request_SignUp)(nil),
		(*Request_Authorize)(nil),
	}
	file_local_chat_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Response_Bool)(nil),
		(*Response_Error)(nil),
		(*Response_SysInited)(nil),
		(*Response_Pong)(nil),
		(*Response_Authorized)(nil),
	}
	file_local_chat_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Update_UserUpdated)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_local_chat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_local_chat_proto_goTypes,
		DependencyIndexes: file_local_chat_proto_depIdxs,
		MessageInfos:      file_local_chat_proto_msgTypes,
	}.Build()
	File_local_chat_proto = out.File
	file_local_chat_proto_rawDesc = nil
	file_local_chat_proto_goTypes = nil
	file_local_chat_proto_depIdxs = nil
}
